### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [mbaroi/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by mbaroi** [comment]
Added the meta viewport tag to the <head> section of my application.html.erb. Seems to be working now. Please let me know!

**Comment by BillyMassey** [comment]
You got it! Good Job!
